start /wait /D config-service mvnw clean install -f pom.xml
start /wait /D eureka-service mvnw clean install -f pom.xml
start /wait /D gateway-service mvnw clean install -f pom.xml
start /wait /D data-service mvnw clean install -f pom.xml
start /wait /D empleado-service mvnw clean install -f pom.xml
start /wait /D justificativo-service mvnw clean install -f pom.xml
start /wait /D horasextras-service mvnw clean install -f pom.xml
start /wait /D calcularplanilla-service mvnw clean install -f pom.xml
start /wait /D mostrarplanilla-service mvnw clean install -f pom.xml