FROM openjdk:17
ARG JAR_FILE=target/horasextras-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} horasextras-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/horasextras-service-0.0.1-SNAPSHOT.jar"]]